basePath: /
definitions:
  model.GetAllStockCodeResponse:
    properties:
      stock_info_list:
        items:
          $ref: '#/definitions/model.StockBasicInfo'
        type: array
    type: object
  model.GetDailyCalcStockDataResponse:
    properties:
      stock_datas:
        items:
          $ref: '#/definitions/model.StockDataItem'
        type: array
    type: object
  model.GetQueryStockDataRequest:
    properties:
      query_data_len:
        type: integer
      stock_list:
        items:
          type: string
        type: array
    type: object
  model.GetQueryStockDataResponse:
    properties:
      stock_datas:
        items:
          $ref: '#/definitions/model.StockDataItem'
        type: array
    type: object
  model.GetRecommandStockRequest:
    properties:
      query_data_len:
        type: integer
      query_date:
        example: "2021-07-01"
        type: string
    type: object
  model.GetRecommandStockResponse:
    properties:
      stock_datas:
        items:
          $ref: '#/definitions/model.StockDataItem'
        type: array
      stock_prediction_datas:
        items:
          $ref: '#/definitions/model.StockPredictItem'
        type: array
    type: object
  model.SinglePredictRecord:
    properties:
      close:
        type: number
      date:
        type: string
      high:
        type: number
      low:
        type: number
      open:
        type: number
    type: object
  model.SingleRecord:
    properties:
      close:
        type: number
      date:
        type: string
      high:
        type: number
      low:
        type: number
      ma13:
        type: number
      ma34:
        type: number
      ma55:
        type: number
      money:
        type: number
      open:
        type: number
      volume:
        type: number
    type: object
  model.StockBasicInfo:
    properties:
      stock_code:
        example: 002142.SZ
        type: string
      stock_name:
        example: 宁波银行
        type: string
    type: object
  model.StockDataItem:
    properties:
      records:
        items:
          $ref: '#/definitions/model.SingleRecord'
        type: array
      stock_code:
        example: 002142.SZ
        type: string
    type: object
  model.StockPredictItem:
    properties:
      prediction_records:
        items:
          $ref: '#/definitions/model.SinglePredictRecord'
        type: array
      stock_code:
        example: 002142.SZ
        type: string
    type: object
info:
  contact:
    email: lrt12250914@outlook.com
    name: Greetlist
    url: http://github.com/greetlist
  description: server API for stock web
  termsOfService: http://github.com/greetlist/
  title: Stock-Show Web API
  version: "1.0"
paths:
  /api/stock/getAllStockCode:
    get:
      description: Return All Stock Code
      operationId: getAllStockCode
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.GetAllStockCodeResponse'
      summary: Query All Stock Code
  /api/stock/getDailyCalcStockData:
    get:
      description: Return All Daily Calc Stock Data
      operationId: getDailyCalcStockData
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.GetDailyCalcStockDataResponse'
      summary: Query Daily Calc Stock Data
  /api/stock/getQueryStockData:
    post:
      consumes:
      - application/json
      description: Return Strategy Sepcific Computed Data
      operationId: getQueryStockData
      parameters:
      - description: Query Stock List
        in: body
        name: request_json
        required: true
        schema:
          $ref: '#/definitions/model.GetQueryStockDataRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.GetQueryStockDataResponse'
      summary: Query Sepcific Stock Computed Data
  /api/stock/getRecommandStockPrediction:
    post:
      consumes:
      - application/json
      description: Return Recommand Stock Prediction Data
      operationId: getRecommandStockPrediction
      parameters:
      - description: Query Date
        in: body
        name: request_json
        required: true
        schema:
          $ref: '#/definitions/model.GetRecommandStockRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.GetRecommandStockResponse'
      summary: Query Recommand Stock Prediction Data
swagger: "2.0"
