basePath: /
definitions:
  model.GetAllStockCodeResponse:
    properties:
      stock_list:
        example:
        - '[''000001'''
        - ' ''002142'''
        - ' ...]'
        items:
          type: string
        type: array
    type: object
  model.GetQueryStockDataRequest:
    properties:
      stock_list:
        items:
          type: string
        type: array
    type: object
  model.GetQueryStockDataResponse:
    properties:
      stock_datas:
        items:
          $ref: '#/definitions/model.StockDataItem'
        type: array
    type: object
  model.SingleRecord:
    properties:
      close:
        type: number
      date:
        type: string
      high:
        type: number
      low:
        type: number
      ma13:
        type: number
      ma34:
        type: number
      ma55:
        type: number
      money:
        type: number
      open:
        type: number
      volume:
        type: number
    type: object
  model.StockDataItem:
    properties:
      records:
        items:
          $ref: '#/definitions/model.SingleRecord'
        type: array
      stock_code:
        example: "002142"
        type: string
    type: object
info:
  contact:
    email: lrt12250914@outlook.com
    name: Greetlist
    url: http://github.com/greetlist
  description: server API for stock web
  termsOfService: http://github.com/greetlist/
  title: Stock-Show Web API
  version: "1.0"
paths:
  /api/stock/getAllStockCode:
    get:
      description: Return All Stock Code
      operationId: getAllStockCode
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.GetAllStockCodeResponse'
      summary: Query All Stock Code
  /api/stock/getDailyStockData:
    get:
      consumes:
      - application/json
      description: Return Strategy Daily Computed Data
      operationId: queryDailyStockData
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: Query Daily Stock Computed Data
  /api/stock/getQueryStockData:
    post:
      consumes:
      - application/json
      description: Return Strategy Sepcific Computed Data
      operationId: getQueryStockData
      parameters:
      - description: Query Stock List
        in: body
        name: request_json
        required: true
        schema:
          $ref: '#/definitions/model.GetQueryStockDataRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.GetQueryStockDataResponse'
      summary: Query Sepcific Stock Computed Data
swagger: "2.0"
